### ISSUE TITLE
doesn't install debs after deploying

### ISSUE THREAD

**Issue by mymike00** [ubports/crossbuilder#16]
after `crossbuilder` deploys all the `deb`s to `/tmp/repo` those aren't installed and I have to do it manually
after entering that dir and `sudo dpkg -i *.deb` and restarting the service/app I'm playing with I can finally see changes

**Comment by mardy** [comment]
Yes, `crossbuilder` normally updates the packages with the ones you built, but if these are new packages (an older version of which was not installed on the device), then nothing happens. This is done for a reason: quite often, a source packages produces some `.deb` packages containing tests, documentation, debugging symbols and other stuff which we generally don't to install on the device, as they consume space. While it's generally easy to filter out documentation and debugging packages, other packages don't follow a clear naming convention so it would not be trivial to filter them out.

I'm closing this -- but if you have some suggestion (or even better, a patch!) don't hesitate to reopen it. :-)

**Comment by mymike00** [comment]
in Telegram, I got a suggestion of using `crossbuilder --no-debs` and it does install the new changes. why?

**Comment by mardy** [comment]
Yes, that works, but it won't build the debian packages. It's still good enough for development, though.
