### ISSUE TITLE
cannot create new container anymore

### ISSUE THREAD

**Issue by mymike00** [ubports/crossbuilder#26]
Today I tried to compile the indicator-display. after messing up a bit with deps I found I didn't have the last xenial commit. I pulled it but I was having some errors. I didn't know what to do so I tried to delete the container and create a new one but the creation failed. [logs here](https://paste.ubuntu.com/p/8hQPs7C4Kc/)
also, output for [lxc info --show-log indicator-display-usdk-16-04-amd64-armhf-dev](https://paste.ubuntu.com/p/qc9YjDJpGT/)

[these](https://paste.ubuntu.com/p/2hZKKcq4X9/) are the logs when I tried to build the indicator after pulling , if you need it

**Comment by UniversalSuperBox** [comment]
Something may have changed with the snap version of lxd. For now, run `crossbuilder --privileged` to get the container running. You might have to `crossbuilder delete` first. Should be fixed by #23.
