### ISSUE TITLE
Error: Remote sdk exists as <https://sdk-images.canonical.com>

### ISSUE THREAD

**Issue by jonnius** [ubports/crossbuilder#6]
I get the following ouput:
```
Building account-plugins for armhf and deploying to device.
Creating LXD container account-plugins-usdk-16-04-amd64-armhf-dev using sdk:ubuntu-sdk-16.04-amd64-armhf-dev.
Error: Remote sdk exists as <https://sdk-images.canonical.com>
Creating account-plugins-usdk-16-04-amd64-armhf-dev
Error: Failed container creation: No storage pool found. Please create a new storage pool.
```
How is `Error: Remote sdk exists as <https://sdk-images.canonical.com>` an error? Shouldn't crossbuilder created the storage pool on the first run?

**Comment by mardy** [comment]
The first one is not an error; I'll eventually get rid of that message, but it's harmless. The error is the second one, about the storage pool. Running

    crossbuilder setup-lxd

will hopefully solve the issue.

**Comment by jonnius** [comment]
It solved it. Thanks!
